### ISSUE TITLE
ECS is launching but not using Aurora serverless database 

### ISSUE THREAD

**Issue by singhindresh** [aws-samples/keycloak-on-aws#226]
Hello,

 ECS is launching successfully but not using Aurora serverless database. I do see all the database parameters are passed correctly but KeyCloak is still using H2. Appreciate if you have any feedback to resolve the issue.

THanks
 Andy

**Comment by wchaws** [comment]
Which region do u use? Some region may not support aurora serverless database. 
Which launch link do you use? You must use either [keycloak-aurora-serverless-from-existing-vpc](https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateUrl=https://aws-gcr-solutions.s3.amazonaws.com/keycloakonaws/latest/keycloak-aurora-serverless-from-existing-vpc.template) or [keycloak-aurora-serverless-from-new-vpc](https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateUrl=https://aws-gcr-solutions.s3.amazonaws.com/keycloakonaws/latest/keycloak-aurora-serverless-from-new-vpc.template) currently
