### ISSUE TITLE
Keycloak clustering 

### ISSUE THREAD

**Issue by stephane-dereppe** [aws-samples/keycloak-on-aws#95]
Hi,

Thanks for the great job you did with this project (and its documentation).

I try to achieve manually (without the cloud formation) the steps you described. Everything works fine if I run only one fargate task.

As soon as I add a second task, the keycloak admin console doesn't work anymore. 

My guess: It's because the clustering is not done between the 2 tasks.

```
[0m[0m20:04:36,334 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [ip-10-0-1-57|0] (1) [ip-10-0-1-57]
```

I see those logs on both tasks.. => I get 2 clusters of one node instead of 1 cluster of 2 nodes.

I the documentation you provide, I didn't noticed anything special about keycloak clustering.

I tried multiple options from the "Clustering" section of [the keycloak docker image documentation](https://hub.docker.com/r/jboss/keycloak) without success.

Is there something I'm missing?

Thanks again

**Comment by wchaws** [comment]
There're two things you need to pay attention,
1. You need to enable ALB sticky session which will route traffic to the same instance. This is a preferred way from the official doc https://www.keycloak.org/docs/latest/server_installation/#sticky-sessions
2. (Optional) Add `JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING` in your container runtime env. This is a kind of service discovery mode for jgroups which's using your database as a central info store. Check https://www.keycloak.org/2019/08/keycloak-jdbc-ping for some details.

**Comment by stephane-dereppe** [comment]
Thanks for the reponse.

I aready found the `JDBC_PING` solution. It works well. The sticky sessions is also an important thing.

For the record, here is the environment variable I added to achieve the JDBC_PING configuration:

* `JGROUPS_DISCOVERY_PROTOCOL= JDBC_PING`
* `JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=java:jboss/datasources/KeycloakDS,initialize_sql="create table if not exists jgroupsping ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data BYTEA DEFAULT NULL, PRIMARY KEY (own_addr, cluster_name))"`

The properties are needed to reference the datasource to use...and to enable the table creation (for a postgres database) By default, the table is not created. So you can provide the creation script.

Reference: 

* http://www.fafonso.com/jgroups/unicast/postgresql/jdbc/ping/cluster/2016/08/07/jgroups-with-postgresql.html
* https://developer.jboss.org/docs/DOC-16351

Maybe you could add a section in your documentation to explain this part. 

Thanks again!

**Comment by wchaws** [comment]
@stephane-dereppe I found the reason why you need to set `initialize_sql ` in `JGROUPS_DISCOVERY_PROPERTIES `. 

From the source code: https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/JDBC_PING.java#L55-L60
```java
    protected String initialize_sql = 
        "CREATE TABLE JGROUPSPING (" +
        "own_addr varchar(200) NOT NULL, " +
        "cluster_name varchar(200) NOT NULL, " +
        "ping_data varbinary(5000) DEFAULT NULL, " +
        "PRIMARY KEY (own_addr, cluster_name) )";
```
The `ping_data varbinary(5000)` data type is not supported in postgres db. therefore, you need to create that table in another way.

**Comment by stephane-dereppe** [comment]
Yep.

Make sense.

Thanks for the information
